"""empty message

Revision ID: c88d801582e5
Revises: 
Create Date: 2021-08-29 00:15:43.911189

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c88d801582e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('first_name', sa.String(length=64), nullable=True),
                    sa.Column('last_name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=True),
                    sa.Column('permissions', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('surfaces',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('class_name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tournament_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('number_rounds', sa.Integer(), nullable=True),
                    sa.Column('maximal_score', sa.Integer(), nullable=True),
                    sa.Column('minimal_score', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tournaments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('old_website_id', sa.Integer(), nullable=True),
                    sa.Column('tournament_topic_url', sa.String(length=64), nullable=True),
                    sa.Column('jeudelorgue_topic_url', sa.String(length=64), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('ended_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.Column('maximal_score', sa.Integer(), nullable=True),
                    sa.Column('current_maximal_score', sa.Integer(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('surface_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['tournament_categories.id'], ),
                    sa.ForeignKeyConstraint(['surface_id'], ['surfaces.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('confirmed', sa.Boolean(), nullable=True),
                    sa.Column('is_old_account', sa.Boolean(), nullable=True),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('annual_points', sa.Integer(), nullable=True),
                    sa.Column('year_to_date_points', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('participants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('matches_not_forecasted', sa.Integer(), nullable=True),
                    sa.Column('score', sa.Integer(), nullable=True),
                    sa.Column('risk_coefficient', sa.Float(), nullable=True),
                    sa.Column('points', sa.Integer(), nullable=True),
                    sa.Column('ranking', sa.Integer(), nullable=True),
                    sa.Column('old_website_id', sa.Integer(), nullable=True),
                    sa.Column('tournament_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rankings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('annual_points', sa.Integer(), nullable=True),
                    sa.Column('annual_ranking', sa.Integer(), nullable=True),
                    sa.Column('annual_number_tournaments', sa.Integer(), nullable=True),
                    sa.Column('year_to_date_points', sa.Integer(), nullable=True),
                    sa.Column('year_to_date_ranking', sa.Integer(), nullable=True),
                    sa.Column('year_to_date_number_tournaments', sa.Integer(), nullable=True),
                    sa.Column('tournament_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tournament_players',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('player_id', sa.Integer(), nullable=True),
                    sa.Column('seed', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=8), nullable=True),
                    sa.Column('qualifier_id', sa.Integer(), nullable=True),
                    sa.Column('tournament_id', sa.Integer(), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('matches',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('round', sa.Integer(), nullable=True),
                    sa.Column('score', sa.String(length=64), nullable=True),
                    sa.Column('tournament_id', sa.Integer(), nullable=True),
                    sa.Column('winner_id', sa.Integer(), nullable=True),
                    sa.Column('tournament_player1_id', sa.Integer(), nullable=True),
                    sa.Column('tournament_player2_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.ForeignKeyConstraint(['tournament_player1_id'], ['tournament_players.id'], ),
                    sa.ForeignKeyConstraint(['tournament_player2_id'], ['tournament_players.id'], ),
                    sa.ForeignKeyConstraint(['winner_id'], ['tournament_players.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('forecasts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('match_id', sa.Integer(), nullable=True),
                    sa.Column('winner_id', sa.Integer(), nullable=True),
                    sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
                    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
                    sa.ForeignKeyConstraint(['winner_id'], ['tournament_players.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasts')
    op.drop_table('matches')
    op.drop_table('tournament_players')
    op.drop_table('rankings')
    op.drop_table('participants')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_table('tournament_categories')
    op.drop_table('surfaces')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('players')
    # ### end Alembic commands ###
